# Generated by Django 4.0.1 on 2022-01-22 10:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('alias', models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_alias', message='Alias can only contain lowercase alphabets, numerals, underscores and hyphens', regex='^[a-z0-9-_]+$')])),
                ('clicks_count', models.PositiveIntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
