# Generated by Django 4.0.1 on 2022-01-22 20:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('alias', models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_alias', message='Alias can only contain lowercase alphabets, numerals, underscores and hyphens', regex='^[a-z0-9-_]+$')])),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_date', models.DateField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('clicks_count', models.PositiveIntegerField(default=0)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_urls.link')),
            ],
        ),
    ]
